{
 "title": "Kubernetes Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodename",
    "label": "Node Name",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespaces",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NotReady Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}==0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pressure Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}==1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}==1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",status=\"true\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Claims",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volumes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "kube_persistentvolume_capacity_bytes/1024/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_persistentvolume_status_phase==1",
     "legendFormat": "State"
    }
   ]
  },
  { "title": "Node Information: $nodename", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$nodename\",resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$nodename\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$nodename\",resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$nodename\",resource=\"cpu\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$nodename\",resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$nodename\",resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$nodename\",resource=\"memory\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$nodename\",resource=\"memory\"})",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "Namespace Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Succeeded Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job last success time from now",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\"})/60/60/24>1",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Pods restart in 30m",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[30m])>1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"}==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "kube_service_spec_type{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_status_reason{namespace=~\"$namespace\", reason=\"Evicted\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Statefulsets",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kube_deployment_status_condition{condition=\"Available\",namespace=~\"$namespace\"}==1",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}