{
 "title": "Physical Server Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server_Address", "label": "Server Address", "query": { "query": "label_values(ServerAddress)" } }
  ]
 },
 "panels": [
  {
   "title": "Status Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Manufacturer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_Health{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "SKU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "Fans Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "PhysicalServer_fanStatus{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "Indicator LED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Manufacturer}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "PhysicalServer_State{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{PowerState}}"
    }
   ]
  },
  {
   "title": "Power Supplies Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "PhysicalServer_powerSupplieStatus{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Network Interfaces Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "PhysicalServer_EthernetInterfaceStatus{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Processors Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "PhysicalServer_processorStatus{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Physical Drives Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "PhysicalServer_PhysicalDriveHealth{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Memory DIMMs Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "PhysicalServer_MemoryDIMMStatus{ServerAddress=\"$Server_Address\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "PhysicalServer_temperatureReading{ServerAddress=\"$Server_Address\"}",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Power Output Watts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "PhysicalServer_serverPowerOutputWattsValue{serverAddress=\"$Server_Address\"}",
     "legendFormat": "{{SerialNumber}}"
    }
   ]
  }
 ]
}