{
 "title": "Proxmox VM",
 "tags": [ "vm" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pve_guest_info, instance)"
    }
   },
   {
    "name": "name",
    "label": "VM Name",
    "query": {
     "query": "label_values(pve_guest_info{instance=\"$instance\"},name)"
    }
   },
   {
    "name": "id",
    "label": "VM ID",
    "query": {
     "query": "label_values(pve_guest_info{name=~\"$name\", instance=~\"$instance\"},id)"
    }
   },
   { "name": "warning", "label": "Warning Threshold", "query": "70" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 98%;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  position: absolute;\n  left: 50%;\n  top: 50%;\n  -ms-transform: translate(-50%, -50%);\n  transform: translate(-50%, -50%);\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: #696969;\n  color: white;\n  border:1px solid #696969;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('http://10.98.12.18:3000/d/wyXTOna4z/home?orgId=1', '_self')\"><span><b style=\"font-size:20px\">&#x2302;</b> HOME</span></button>\n\n</body>\n</html>"
   }
  },
  {
   "title": "Overview Infomation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(pve_up{instance=~\"$instance\", id=\"$id\"} == 1)"
    }
   ]
  },
  {
   "title": "CPU Usage > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_cpu_usage_ratio{instance=\"$instance\", id=\"$id\"} / pve_cpu_usage_limit{instance=\"$instance\", id=\"$id\"} * 100 > $warning)"
    }
   ]
  },
  {
   "title": "Memory Usage > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_memory_usage_bytes{instance=\"$instance\", id=\"$id\"} / pve_memory_size_bytes{instance=\"$instance\", id=\"$id\"} * 100 > $warning)"
    }
   ]
  },
  {
   "title": "VM's Resource Usage",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\", id=\"$id\"}"
    },
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\", id=\"$id\"} / pve_memory_size_bytes{instance=\"$instance\", id=\"$id\"}"
    },
    {
     "expr": "sum by(id) (pve_cpu_usage_limit{instance=\"$instance\", id=\"$id\"})"
    },
    {
     "expr": "sum by(id) (pve_disk_size_bytes{instance=\"$instance\", id=\"$id\"})"
    },
    {
     "expr": "sum by(id) (pve_up{instance=~\"$instance\", id=\"$id\"})"
    }
   ]
  },
  {
   "title": "$name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "vmname",
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{instance=\"$instance\", id=\"$id\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Cpu usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_vm_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "Memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_vm_memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit{instance=\"$instance\", id=\"$id\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\", id=\"$id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk read average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_disk_read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk write average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_disk_write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Received Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Network received average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:proxmox_network_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "id::tag", "operator": "=~", "value": "/^$id$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Transmitted Average",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Network transmitted average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       {
        "params": [
         "job:proxmox_network_transmitted"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}