{
 "title": "VMWare VM",
 "tags": [ "vm" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vmware_host_cpu_idle_summation, host_name)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(vmware_vm_num_cpu,vm_name)"
    }
   },
   { "name": "warning", "label": "Warning Threshold", "query": "70" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\n.back {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n}\n\n.button {\n  display: inline-block;\n  background-color: #2266ee;\n  border: none;\n  color: white;\n  text-align: center;\n  font-size: 14px;\n  width: 98%;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid #2266ee;\n  font-weight: bold;\n  opacity: 1;\n  position: absolute;\n  left: 50%;\n  top: 50%;\n  -ms-transform: translate(-50%, -50%);\n  transform: translate(-50%, -50%);\n  margin:2px\n}\n\n.clicked {\n  display: inline-block;\n  background-color: white;\n  border: none;\n  color: grey;\n  text-align: center;\n  font-size: 14px;\n  width: 10em;\n  height: 45px;\n  transition: all 0.5s;\n  cursor: pointer;\n  border-radius: 5px;\n  border:1px solid grey;\n  font-weight: bold;\n  margin:2px;\n  float: right;\n}\n.button:hover {\n  background-color: #696969;\n  color: white;\n  border:1px solid #696969;\n}\n\n</style>\n</head>\n<body>\n\n<button class=\"button\" style=\"vertical-align:middle\" onclick=\"window.open('http://10.98.12.18:3000/d/wyXTOna4z/home?orgId=1', '_self')\"><span><b style=\"font-size:20px\">&#x2302;</b> HOME</span></button>\n\n</body>\n</html>"
   }
  },
  {
   "title": "Overview Infomation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VM UP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_power_state{host_name=~\"$instance\", vm_name=\"$name\"} == 1)"
    }
   ]
  },
  {
   "title": "CPU Usage > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_cpu_usagemhz_average{host_name=\"$instance\", vm_name=\"$name\"} / vmware_vm_max_cpu_usage {host_name=\"$instance\", vm_name=\"$name\"} * 100 > $warning)"
    }
   ]
  },
  {
   "title": "Memory Usage > $warning%",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_mem_usage_average{host_name=\"$instance\", vm_name=\"$name\"} / vmware_vm_memory_max{host_name=\"$instance\", vm_name=\"$name\"} * 100 > $warning)"
    }
   ]
  },
  {
   "title": "$name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "vmname",
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_disk_capacity{host_name=\"$instance\", vm_name=\"$name\", partition=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "job:vmware_vm_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "vm_name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "vmware_vm_mem_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "vm_name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{host_name=\"$instance\", vm_name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{host_name=\"$instance\", vm_name=\"$name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Disk read average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "vmware_vm_disk_read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "vm_name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Disk write average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "vmware_vm_disk_write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "vm_name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Received Average",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Network received average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "vmware_vm_net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "vm_name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Receive/Transmit Bandwidth (Network)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       {
        "params": [
         "vmware_vm_net_transmitted_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "vm_name::tag", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  }
 ]
}